# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-13 15:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=1000)),
                ('author', models.CharField(max_length=150)),
                ('date', models.DateField(verbose_name='comment date')),
                ('billboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='billboard.Billboard')),
            ],
        ),
    ]
